// <auto-generated />
namespace WebProje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deneme_reverse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deneme_reverse));
        
        string IMigrationMetadata.Id
        {
            get { return "201904300721595_deneme_reverse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
